Repository unb-mds/mapadaacessibilidade, pull requests merged in 2025-05, with the labels that each got.

#32 Update DER.md
  docs/databases/DER.md
Labels: documentation

#50 Db backend
  backend/db/.env.example
  backend/db/readme.md
  backend/db/schema.sql.sql
Labels: infrastructure

#51 Dev backend
  app/backend/src/config/db.js
  app/backend/src/controllers/auth.js
  app/backend/src/controllers/locations.js
  app/backend/src/middleware/auth.js
  app/backend/src/models/Location.js
  app/backend/src/models/User.js
  app/backend/src/routes/auth.js
  app/backend/src/routes/locations.js
  app/backend/src/utils/geocoder.js
  src/config/db.js
  src/controllers/auth.js
  src/controllers/locations.js
  src/middleware/auth.js
  src/models/Location.js
  src/models/User.js
  src/routes/auth.js
  src/routes/locations.js
  src/routes/server.js
  src/utils/geocoder.js
Labels: backend

#54 Revert "Dev backend"
  app/backend/src/config/db.js
  app/backend/src/controllers/auth.js
  app/backend/src/controllers/locations.js
  app/backend/src/middleware/auth.js
  app/backend/src/models/Location.js
  app/backend/src/models/User.js
  app/backend/src/routes/auth.js
  app/backend/src/routes/locations.js
  app/backend/src/utils/geocoder.js
  src/config/db.js
  src/controllers/auth.js
  src/controllers/locations.js
  src/middleware/auth.js
  src/models/Location.js
  src/models/User.js
  src/routes/auth.js
  src/routes/locations.js
  src/routes/server.js
  src/utils/geocoder.js
Labels: bug

#60 📚 | Alterações na documentação
  Documentação/Atas/sprint-6.md
Labels: documentation

#66 Backend
  app/backend/prisma/schema.prisma
Labels: backend

#74 ✨ Nova Feature - Frontend
  README.md
  app/package.json
  app/src/pages/Signup/signup.jsx
  app/src/pages/Signup/styleSignup.css
Labels: enhancement, frontend
