Repository unb-mds/mapadaacessibilidade, pull requests merged in 2025-07, with the labels that each got.

#122 Clean code
  .github/workflows/Lint.yml
  .github/workflows/backendTest.yml
  .github/workflows/frotendTest.yml
  README.md
  app/backend/API-SWAGGER/swaggerComponents.js
  app/backend/db/readmedb.md
  app/backend/src/controllers/acessibilidadeLocalController.js
  app/backend/src/controllers/avaliacaoLocalController.js
  app/backend/src/controllers/avaliacaoLocalController.test.js
  app/backend/src/controllers/fotosController.js
  app/backend/src/controllers/fotosController.test.js
  app/backend/src/controllers/locaisController.js
  app/backend/src/controllers/locaisController.test.js
  app/backend/src/controllers/usuariosController.js
  app/backend/src/jest.config.js
  app/backend/src/middlewares/authMiddleware.js
  app/backend/src/middlewares/loginMiddleware.js
  app/backend/src/routes/acessibilidadeLocalRouter.js
  app/backend/src/routes/acessibilidadeRouter.js
  app/backend/src/routes/avaliacaoLocalRouter.js
  app/backend/src/routes/fotosRouter.js
  app/backend/src/routes/usuariosRoutes.js
  app/backend/src/server.js
  app/frontend/src/App.jsx
  app/frontend/src/components/Footer.jsx
  app/frontend/src/components/Header.css
  app/frontend/src/components/Header.jsx
  app/frontend/src/components/footer.css
  app/frontend/src/hooks/use-toast.js
  app/frontend/src/index.css
  app/frontend/src/main.jsx
  app/frontend/src/pages/Cadastro.css
  app/frontend/src/pages/Cadastro.jsx
  app/frontend/src/pages/Contato.css
  app/frontend/src/pages/Contato.jsx
  app/frontend/src/pages/Eventos.css
  app/frontend/src/pages/Eventos.jsx
  app/frontend/src/pages/FAQ.css
  app/frontend/src/pages/FAQ.jsx
  app/frontend/src/pages/Home.css
  app/frontend/src/pages/Home.jsx
  app/frontend/src/pages/Local.css
  app/frontend/src/pages/Local.jsx
  app/frontend/src/pages/Login.css
  app/frontend/src/pages/Login.jsx
  app/frontend/src/pages/Sobre.css
  app/frontend/src/pages/Sobre.jsx
  app/frontend/vite.config.js
Labels: infrastructure

#126 fix arquitetura
  Documentação/docos/Arquitetura/Arquitetura.md
  Documentação/docos/Arquitetura/EscolhaDasStacksBackend.md
  Documentação/docos/Database/DER.md
  Documentação/docos/Database/DLD.md
  Documentação/docos/Database/DLDimage.md
  Documentação/docos/Database/PostgreSQL/mapcom_acess_db.md
  Documentação/docos/Database/PostgreSQL/script_fisico.sql
  Documentação/docos/Database/integracao_db.md
  Documentação/docos/Requisitos/.gitkeep
  Documentação/docos/Requisitos/Engenharia-de-requisitos.md
Labels: documentation, backend

#139 Atualização de atas
  Documentação/Atas/sprint-10.md
  Documentação/Atas/sprint-11.md
  Documentação/Atas/sprint-9.md
Labels: documentation
